[package]
name = "nix-deploy"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
rnix = "0.11.0"
ssh2 = "0.9.4"
tokio = { version = "1.40.0", features = ["full"] }
